[package]
name = "blankwindow-gtk-rs"
version = "0.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
debug_print = "*"
dirs = "6.0.0"
glib = "0.21.3"
gtk = { package = "gtk4", version = "0.10.0" }
